import { createContext, useState } from "react";

export const DataContext = createContext();

export const DataProvider = ({ children }) => {
  const [parties, setParties] = useState([]);

  const [simpleParties, setSimpleParties] = useState([
    {
      name: "Prawo i Sprawiedliwość",
      shortName: "PiS",
      isOverThreshold: true,
      color: "#175aa7",
      result: 0,
    },
    {
      name: "Koalicja Obywatelska",
      shortName: "KO",
      isOverThreshold: true,
      color: "#f9641d",
      result: 0,
    },
    {
      name: "Konfederacja",
      shortName: "KWiN",
      isOverThreshold: true,
      color: "#1a2e4d",
      result: 0,
    },
    {
      name: "Trzecia Droga",
      shortName: "TD",
      isOverThreshold: true,
      color: "#96cc22",
      result: 0,
    },
    {
      name: "Lewica",
      shortName: "Lewica",
      isOverThreshold: true,
      color: "#e0002a",
      result: 0,
    },
    {
      name: "Bezpartyjni Samorządowcy",
      shortName: "BS",
      isOverThreshold: false,
      color: "#000000",
      result: 0,
    },
    {
      name: "Pozostałe komitety",
      shortName: "inne",
      isOverThreshold: false,
      color: "#999999",
      result: 100,
    },
  ]);
  const [euroParties, setEuroParties] = useState([
    {
      name: "Prawo i Sprawiedliwość",
      shortName: "PiS",
      isOverThreshold: true,
      color: "#175aa7",
      result: 0,
    },
    {
      name: "Koalicja Europejska",
      shortName: "KE",
      isOverThreshold: true,
      color: "#f9641d",
      result: 0,
    },
    {
      name: "Konfederacja",
      shortName: "KWiN",
      isOverThreshold: true,
      color: "#1a2e4d",
      result: 0,
    },
    {
      name: "Pozostałe komitety",
      shortName: "inne",
      isOverThreshold: false,
      color: "#999999",
      result: 100,
    },
  ]);
  const [districts, setDistricts] = useState([]);
  const [simpleDistricts, setSimpleDistricts] = useState([
    {
      name: "Legnica (1)",
      deputies: 12,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "dl",
    },
    {
      name: "Wałbrzych (2)",
      deputies: 8,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "db",
    },
    {
      name: "Wrocław (3)",
      deputies: 14,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "dw",
    },
    {
      name: "Bydgoszcz (4)",
      deputies: 12,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "cb",
    },
    {
      name: "Toruń (5)",
      deputies: 13,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "ct",
    },
    {
      name: "Lublin (6)",
      deputies: 15,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "lu",
    },
    {
      name: "Chełm (7)",
      deputies: 12,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "lc",
    },
    {
      name: "Zielona Góra (8)",
      deputies: 12,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "fz",
    },
    {
      name: "Łódź (9)",
      deputies: 10,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "el",
    },
    {
      name: "Piotrków Trybunalski (10)",
      deputies: 9,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "ep",
    },
    {
      name: "Sieradz (11)",
      deputies: 12,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "esi",
    },
    {
      name: "Chrzanów (12)",
      deputies: 8,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "kch",
    },
    {
      name: "Kraków	(13)",
      deputies: 14,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "kr",
    },
    {
      name: "Nowy Sącz (14)",
      deputies: 10,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "kn",
    },
    {
      name: "Tarnów	(15)",
      deputies: 9,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "kt",
    },
    {
      name: "Płock (16)",
      deputies: 10,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "wp",
    },
    {
      name: "Radom (17)",
      deputies: 9,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "wr",
    },
    {
      name: "Siedlce (18)",
      deputies: 12,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "ws",
    },
    {
      name: "Warszawa (19)",
      deputies: 20,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "wa",
    },
    {
      name: "Warszawa – obwarzanek (20)",
      deputies: 12,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "wb",
    },
    {
      name: "Opole (21)",
      deputies: 12,
      method: "dhondt",
      parties: [
        ...simpleParties,
        {
          name: "Mniejszość Niemiecka",
          shortName: "MN",
          isOverThreshold: true,
          color: "#fcd031",
          result: 0,
        },
      ],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "op",
    },
    {
      name: "Krosno (22)",
      deputies: 11,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "rk",
    },
    {
      name: "Rzeszów (23)",
      deputies: 15,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "rz",
    },
    {
      name: "Białystok (24)",
      deputies: 14,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "bi",
    },
    {
      name: "Gdańsk (25)",
      deputies: 12,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "gd",
    },
    {
      name: "Słupsk / Gdynia (26)",
      deputies: 14,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "gs",
    },
    {
      name: "Bielsko-Biała (27)",
      deputies: 9,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "sb",
    },
    {
      name: "Częstochowa (28)",
      deputies: 7,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "sc",
    },
    {
      name: "Gliwice (29)",
      deputies: 9,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "sg",
    },
    {
      name: "Rybnik (30)",
      deputies: 9,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "sr",
    },
    {
      name: "Katowice	(31)",
      deputies: 12,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "sk",
    },
    {
      name: "Sosnowiec (32)",
      deputies: 9,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "so",
    },
    {
      name: "Kielce	(33)",
      deputies: 16,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "tk",
    },
    {
      name: "Elbląg (34)",
      deputies: 8,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "ne",
    },
    {
      name: "Olsztyn (35)",
      deputies: 10,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},

      id: "no",
    },
    {
      name: "Kalisz (36)",
      deputies: 12,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "pk",
    },
    {
      name: "Konin (37)",
      deputies: 9,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "pn",
    },
    {
      name: "Piła (38)",
      deputies: 9,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "pp",
    },
    {
      name: "Poznań (39)",
      deputies: 10,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "po",
    },
    {
      name: "Koszalin (40)",
      deputies: 8,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "zk",
    },
    {
      name: "Szczecin (41)",
      deputies: 12,
      method: "dhondt",
      parties: [...simpleParties],
      showFinalResult: false,
      finalResult: [],
      forChart: {},
      id: "zs",
    },
  ]);
  const [selectedSimpleDistrict, setSelectedSimpleDistrict] = useState("");

  const providerValue = {
    parties,
    setParties,
    districts,
    setDistricts,
    simpleParties,
    setSimpleParties,
    simpleDistricts,
    setSimpleDistricts,
    selectedSimpleDistrict,
    setSelectedSimpleDistrict,
    euroParties,
    setEuroParties,
  };

  return (
    <DataContext.Provider value={providerValue}>
      {children}
    </DataContext.Provider>
  );
};

export default DataProvider;
